import type { PaginatedResponse, Product } from '@/types';
import { apiClient } from '@/utils';

/**
 * Product Service - Handles all product-related API calls
 * 
 * Why a service:
 * - Centralizes all product endpoints in one place
 * - Makes it easy to change endpoint URLs
 * - Encapsulates business logic (filtering, pagination)
 * - Easier to test and mock
 * 
 * Usage in components:
 * import { productService } from '@/services/productService';
 * 
 * const products = await productService.getAll();
 * const product = await productService.getById(123);
 */

export interface ProductReview {
  id: number;
  userId: number;
  userName: string;
  rating: number;
  comment: string;
  createdAt: string;
}

export interface CreateReviewRequest {
  rating: number;
  comment: string;
}

export const productService = {
  /**
   * Get all products with pagination
   * 
   * @param skip - Number of products to skip (for pagination)
   * @param limit - Number of products per page
   * @param signal - AbortSignal for request cancellation
   * @returns Paginated list of products with total count
   * 
   * Example:
   * const response = await productService.getAll(0, 10);
   * // Returns first 10 products with total count
   */
  getAll: (skip: number = 0, limit: number = 10, signal?: AbortSignal) =>
    apiClient.get<PaginatedResponse<Product>>(
      `/products?skip=${skip}&limit=${limit}`,
      { signal }
    ),

  /**
   * Get all available product categories
   * 
   * @param signal - AbortSignal for request cancellation
   * @returns Array of category slugs
   * 
   * Example:
   * const categories = await productService.getCategories();
   * // Returns ['smartphones', 'laptops', 'fragrances', ...]
   */
  getCategories: (signal?: AbortSignal) =>
    apiClient.get<string[]>('/products/categories', { signal }),

  /**
   * Get all available product brands
   * 
   * @param signal - AbortSignal for request cancellation
   * @returns Array of brand names
   * 
   * Example:
   * const brands = await productService.getBrands();
   * // Returns ['Apple', 'Samsung', 'Sony', ...]
   */
  getBrands: (signal?: AbortSignal) =>
    apiClient.get<string[]>('/products/brands', { signal }),

  /**
   * Get a single product by ID
   * 
   * @param id - Product ID
   * @param signal - AbortSignal for request cancellation
   * @returns Single product with all details and reviews
   * 
   * Example:
   * const product = await productService.getById(1);
   */
  getById: (id: number, signal?: AbortSignal) =>
    apiClient.get<Product>(`/products/${id}`, { signal }),

  /**
   * Search products by query
   * 
   * @param query - Search term
   * @param skip - Number of results to skip
   * @param limit - Number of results per page
   * @param signal - AbortSignal for request cancellation
   * @returns Filtered products matching search query
   * 
   * Example:
   * const results = await productService.search('laptop');
   */
  search: (query: string, skip: number = 0, limit: number = 10, signal?: AbortSignal) =>
    apiClient.get<PaginatedResponse<Product>>(
      `/products/search?q=${query}&skip=${skip}&limit=${limit}`,
      { signal }
    ),

  /**
   * Get products by category
   * 
   * @param category - Product category name
   * @param skip - Number of results to skip
   * @param limit - Number of results per page
   * @param signal - AbortSignal for request cancellation
   * @returns Products in the specified category
   * 
   * Example:
   * const electronics = await productService.getByCategory('electronics');
   */
  getByCategory: (category: string, skip: number = 0, limit: number = 10, signal?: AbortSignal) =>
    apiClient.get<PaginatedResponse<Product>>(
      `/products/category/${category}?skip=${skip}&limit=${limit}`,
      { signal }
    ),

  /**
   * Get product reviews
   * 
   * @param productId - Product ID
   * @param signal - AbortSignal for request cancellation
   * @returns List of reviews for the product
   * 
   * Example:
   * const reviews = await productService.getReviews(123);
   */
  getReviews: (productId: number, signal?: AbortSignal) =>
    apiClient.get<ProductReview[]>(`/products/${productId}/reviews`, { signal }),

  /**
   * Add a review to a product
   * 
   * Requires authentication.
   * 
   * @param productId - Product ID to review
   * @param review - Review data (rating and comment)
   * @returns Created review
   * 
   * Example:
   * const review = await productService.addReview(123, {
   *   rating: 5,
   *   comment: 'Great product!'
   * });
   */
  addReview: (productId: number, review: CreateReviewRequest) =>
    apiClient.post<ProductReview>(`/products/${productId}/reviews`, review),

  /**
   * Create a new product (admin only)
   * 
   * @param product - Product data (id will be generated by server)
   * @returns Created product with assigned ID
   * 
   * Example:
   * const newProduct = await productService.create({
   *   title: 'New Product',
   *   price: 99.99,
   *   category: 'electronics',
   *   ...
   * });
   */
  create: (product: Omit<Product, 'id' | 'reviews'>) =>
    apiClient.post<Product>('/products', product),

  /**
   * Update an existing product (admin only)
   * 
   * @param id - Product ID to update
   * @param updates - Fields to update (partial update)
   * @returns Updated product
   * 
   * Example:
   * const updated = await productService.update(1, { price: 89.99 });
   */
  update: (id: number, updates: Partial<Product>) =>
    apiClient.put<Product>(`/products/${id}`, updates),

  /**
   * Delete a product (admin only)
   * 
   * @param id - Product ID to delete
   * @returns Deleted product data
   * 
   * Example:
   * await productService.delete(1);
   */
  delete: (id: number) =>
    apiClient.delete<Product>(`/products/${id}`),
};
